config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  
  get 'welcome/index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login' , to: 'sessions#new', as: 'login'
  get 'logout' , to: 'sessions#destroy', as: 'logout'
  
  resources :articles do
    resources :comments
    resources :reviews
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image
    
    belongs_to :user
    
    has_many :comments, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    validates :title, presence: true, length: { minimum: 5 }
    validates :text, presence: true, length: { minimum: 10 }
    validates :image, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    
    VALID_EMAIL_REGEX = /A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    #password requires at least one capital letter, number and symbol
    VALID_PASSOWORD_REGEX = /(?=[A-Z])(?=.+[0-9])(?=.+[!@#$^&*])/ 
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 12, minimum:6 }
        
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 },
        format: {with: VALID_PASSOWORD_REGEX}
        
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end  
             
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
    def new
        @article = Article.new
    end
    
    def index
        @articles = Article.all
    end 
    
    def show
       @article = Article.find(params[:id])
    end
  
    def create
      @article = Article.new(article_params)
      @article.user = current_user 
     # byebug
      
    if @article.save
        #byebug
     redirect_to @article
    else
     render 'new'
    end
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update 
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else 
            render 'edit'
        end 
    end 
    
    def destroy 
        @article = Article.find(params[:id])
        @article.destroy
        
        redirect_to articles_path
        
    end
        
end

private 
    def article_params
        params.require(:article).permit(:title, :text, :image)
    end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
    end
    
    def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
    end
    
    private 
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
    @article = Article.find(params[:article_id])
    @review = @article.reviews.create(review_params)
    redirect_to article_path(@article)
    end
    
    
    def destroy
    @article = Article.find(params[:article_id])
    @review = @article.reviews.find(params[:id])
    @review.destroy
    redirect_to article_path(@article)
    end
    
    
    private 
        def review_params
            params.require(:review).permit(:commenter, :body, :rating)
        end
        
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

 <%= render 'form.html.erb' %>
 
<p class="Back">
    <%= link_to 'Back', articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<hr>

<div>
    <%= render 'navigation/index' %>
</div>

<h3 style="text-align:left;">
 <%= link_to 'New article', new_article_path %>
</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><% if article.user %>
          <%= article.user.name %>
          <% end %>
      </td>
      
      
      
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy',
                             article_path(article),
                             method: :delete,
                             data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<div>
    <%= render 'navigation/index' %>
</div>


<%= render 'form.html.erb' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<style>
img{
  width:900px;
  height:400px;
  object-fit:cover; 
}

  
</style>


<div>
    <%= render 'navigation/index' %>
</div>


<div class"img">
      <%= image_tag(@article.image) %>
</div>
 
<div class = "articleBody">

  <div></div>
  
  <div> 
  
      <div>
        <br>
        <strong><%= @article.title %> </strong>
        <br>
        <br>
      </div>
      
  
      <div <div class = "articleText">
        <%= @article.text %>
      </div>
    
  </div>
  <div></div>

</div>


<div class = "articleSections">
  <div>
    <%= render @article.reviews %>
  </div>
  <div>
     <%= render 'reviews/form' %>
  </div>
</div>

app/views/comments/_comment.html.erb
<p>
    <div class= "commentsFormat">
        <u>Name:</u>
        <%= comment.commenter %>
        <br>
        <br>
        <div class = "commentBody">
            <%= comment.body %>
        </div>
        
        <br>
    </div>
    
</p>

<div class = "deleteCommentFormat">
    <%= link_to 'Delete Comment', [comment.article, comment],
                method: :delete, 
                data: { confirm: 'Are you sure?'} %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/navigation/_index.html.erb
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  position: -webkit-sticky; /* Safari */
  position: sticky;

}

li {
  float: left;
  border-right: 1px solid #bbb;
  
}

li a{
  color: white;
  display: block;
  text-align: center;
  font-size: 16px;
  padding: 14px 16px;
  text-decoration: none;

}

li a:hover {
  background-color: #111;
}

li:last-child {
  border-right: none;
}

</style>

<ul>
    
<li><%= link_to 'Home', controller: 'welcome' %></li>

<li> <%= link_to 'My Blog', controller: 'articles' %> </li>

<li style="float:right" >
    
    <ul style="float:right">
      <li>
         <% if current_user %>
        Hello, <%= current_user.name%>
        <br>
      </li>
   
    
    <li>
      <%= link_to 'Log Out', logout_path %>
    <% else %>
    </li>  
    
    <li>
      <%= link_to 'Sign Up', signup_path %>
    </li>
    
    <li>
    <%= link_to 'Log In', login_path %>
    <% end %>
    </li>
    
    </ul>
    
</li> 

</ul>

app/views/reviews/_form.html.erb
<%= simple_form_for([@article, @article.reviews.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.input_field :commenter, required: true %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.input_field :body, required: true %>
  </p>
  <p>
      <%= f.label :rating %><br>
      <%= f.input_field :rating, as: :radio_buttons, collection: 1..5, required: true %>
  </p>
  <p>
    <%= f.button :submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<p>
    <div class= "reviewsFormat">
        <u>Name:</u>
        <%= review.commenter %>
        <br>
        <br>
        <div class = "reviewBody">
            <p>Comment: <%= review.body %> </p>
            <p>Rating:  <%= review.rating %> </p>
        </div>
        <br>
    </div>
    
</p>

<div class = "deleteReviewFormat">
    <%= link_to 'Delete Review', [review.article, review],
                method: :delete, 
                data: { confirm: 'Are you sure?'} %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div>
    <%= render 'navigation/index' %>
</div>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello, Blog App User!</h1>
<hr>

<%= render 'navigation/index' %>